language: CPP
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install build-essential libtool autotools-dev autoconf libssl-dev pkg-config
  - sudo apt-get install libboost1.48-dev libboost-chrono1.48-dev libboost-filesystem1.48-dev libboost-program-options1.48-dev libboost-system1.48-dev libboost-test1.48-dev libboost-thread1.48-dev
  - sudo apt-get install libdb++-dev
  - sudo apt-get install libqt4-dev 
  - sudo apt-get instal  libprotobuf-dev protobuf-compiler
script:
  - ./autogen.sh
  - ./configure CFLAGS="-O3"
  - make