name: dogecoin-core
version: "1.10"
summary: Dogecoin Core
description: Dogecoin Core is the reference Dogecoin client and it builds the backbone of the network. However, it downloads and stores the entire history of Dogecoin transactions (which is currently several GBs); depending on the speed of your computer and network connection, the synchronization process can take anywhere from a few hours to a day or more.
confinement: strict
grade: stable
type: app
icon: src/qt/res/icons/bitcoin.png

apps:
  dogecoin-qt:
    command: qt4-launch bin/dogecoin-qt.wrapper
    desktop: usr/share/applications/dogecoin-qt.desktop
    plugs: [network, network-bind, unity7, process-control]
  dogecoin-cli:
    command: bin/dogecoin-cli.wrapper
    plugs:
      - network
  dogecoin-tx:
    command: bin/dogecoin-tx

parts:
  dogecoin:
    plugin: autotools
    source: .
    configflags:
      - --with-gui=qt4
      - --with-incompatible-bdb
      - --with-miniupnpc=no
      - --without-tests
    build-packages:
      - autoconf
      - autotools-dev
      - bsdmainutils
      - build-essential
      - libboost-all-dev                                                       
      - libdb++-dev
      - libprotobuf-dev
      - libqrencode-dev
      - libqt4-dev
      - libssl-dev
      - libtool
      - pkg-config
      - protobuf-compiler
    stage-packages:
      - libqtgui4
    after: [qt4conf]
  fold-ins:
    plugin: dump
    source: .
    prepare: |
      sed 's|Icon=dogecoin128|Icon=/snap/dogecoin-core/current/meta/gui/icon.png|' -i contrib/debian/dogecoin-qt.desktop
    organize:
      snap_cli_app_wrapper: bin/dogecoin-cli.wrapper
      snap_gui_app_wrapper: bin/dogecoin-qt.wrapper
      contrib/debian/dogecoin-qt.desktop: usr/share/applications/dogecoin-qt.desktop
    stage:
      - bin/dogecoin-cli.wrapper
      - bin/dogecoin-qt.wrapper
      - usr/share/applications/dogecoin-qt.desktop
    prime:
      - bin/dogecoin-cli.wrapper
      - bin/dogecoin-qt.wrapper
      - usr/share/applications/dogecoin-qt.desktop
