name: Windows GUI build

on:
  push:
    branches:
    - master
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  BDB_PREFIX: /usr/local

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
      with:
         fetch-depth: 1

    - name: Cache dependencies
      uses : actions/cache@v2
      with:
         path: | 
          ${{github.workspace}}/dependencies/sources
          ${{github.workspace}}/dependencies/work
          ${{github.workspace}}/dependencies/x86_64-w64-mingw32
          ${{github.workspace}}/dependencies/built
         key: ${{ runner.os }}-x86_64-w64-mingw32-${{ hashFiles('${{github.workspace}}/dependencies/Makefile') }}

    - name: Install packages Ubuntu
      run: | 
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -yq build-essential libtool autotools-dev \
             automake pkg-config bsdmainutils curl g++-mingw-w64-x86-64 mingw-w64-x86-64-dev
    
    - name: Build and install dependencies
      run: |
        cd ${{github.workspace}}/depends
        make HOST=x86_64-w64-mingw32
        ls -l 
        cd ${{github.workspace}}    
    
    - name: Build CoinGreen
      run: |
        cd ${{github.workspace}}
        ./autogen.sh
        CONFIG_SITE=$PWD/depends/x86_64-w64-mingw32/share/config.site ./configure --prefix=/
#        make

#    - name: Run tests
#      run: |
#        cd ${{github.workspace}}
#        make check

#    - name: Install
#      run: |
#        cd ${{github.workspace}}
#        sudo make install

#    - uses: actions/upload-artifact@v2
#      with:
#         path: ${{github.workspace}}/src/qt/*.exe
